db.url=jdbc:sqlserver://localhost:1433;databaseName=urbanpulse;encrypt=true;trustServerCertificate=true
db.username=sa
db.password=Ronaldo
db.driver=com.microsoft.sqlserver.jdbc.SQLServerDriver

jwt.secret=urbanpulse-super-secret-key-change-me-1234567890
jwt.expiration-ms=86400000